<?php

return array(
    0 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/wp-seo.php',
        'fileSize' => 1658,
        'visibility' => null,
        'lastModified' => 1752568680,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    1 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/admin',
        'visibility' => null,
        'lastModified' => 1752137378,
        'extraMetadata' => array(),
    ),
    2 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/wp-seo-main.php',
        'fileSize' => 17035,
        'visibility' => null,
        'lastModified' => 1752568680,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    3 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/src',
        'visibility' => null,
        'lastModified' => 1752137378,
        'extraMetadata' => array(),
    ),
    4 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/css',
        'visibility' => null,
        'lastModified' => 1752568680,
        'extraMetadata' => array(),
    ),
    5 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/vendor',
        'visibility' => null,
        'lastModified' => 1752568680,
        'extraMetadata' => array(),
    ),
    6 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/vendor_prefixed',
        'visibility' => null,
        'lastModified' => 1718702102,
        'extraMetadata' => array(),
    ),
    7 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/images',
        'visibility' => null,
        'lastModified' => 1751370860,
        'extraMetadata' => array(),
    ),
    8 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/readme.txt',
        'fileSize' => 15320,
        'visibility' => null,
        'lastModified' => 1752568680,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    9 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/packages',
        'visibility' => null,
        'lastModified' => 1744019165,
        'extraMetadata' => array(),
    ),
    10 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/lib',
        'visibility' => null,
        'lastModified' => 1744019165,
        'extraMetadata' => array(),
    ),
    11 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/blocks',
        'visibility' => null,
        'lastModified' => 1716476931,
        'extraMetadata' => array(),
    ),
    12 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/inc',
        'visibility' => null,
        'lastModified' => 1751370860,
        'extraMetadata' => array(),
    ),
    13 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/index.php',
        'fileSize' => 38,
        'visibility' => null,
        'lastModified' => 1437485849,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    14 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/wpml-config.xml',
        'fileSize' => 2131,
        'visibility' => null,
        'lastModified' => 1664975468,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    15 => array(
        'type' => 'file',
        'path' => 'wordpress-seo/tags/25.5/license.txt',
        'fileSize' => 33319,
        'visibility' => null,
        'lastModified' => 1521562744,
        'mimeType' => 'text/xml; charset="utf-8"',
        'extraMetadata' => array(),
    ),
    16 => array(
        'type' => 'dir',
        'path' => 'wordpress-seo/tags/25.5/js',
        'visibility' => null,
        'lastModified' => 1752137378,
        'extraMetadata' => [],
    ),
);
